### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by andrey-vasilyev** [ogorodni/calc#1]
1. Please fix the build
2. You have multiple **different** java versions in you main pom
3. Try to integrate with GitHub's CI to make sure you do not break a build next time. Read https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-maven
4. lets try and build an expression tree with Antlr parser, to make the task easier lets not care about parenthesis 
5. tests for antrl calculator?
6. use antlr maven plugin to generate parser at build time

**Comment by ogorodni** [comment]
fixed
